<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>    
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>






  <ItemGroup>
    <ProjectReference Include="..\BlazorServerBotVision.Application\BlazorServerBotVision.Application.csproj" />
    <ProjectReference Include="..\BlazorServerBotVision.Shared\BlazorServerBotVision.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.5" />
  </ItemGroup> 

  <PropertyGroup>
    <AssemblyName>BlazorServerBotVision.UI</AssemblyName>
    <RootNamespace>BlazorServerBotVision.UI</RootNamespace>
  </PropertyGroup>

</Project>
